package edu.cad.domain;

public enum OtherLoadType {
    SCI_RESEARCH_INDIVIDUAL,
    PRACTICE_MANAGEMENT,
    ATTESTATION_MANAGEMENT,
    ATTESTATION_CONSULTING,
    ATTESTATION_REVIEW,
    EXAM_CONSULTING,
    EXAM_COMMISSION_DIPLOMA,
    EXAM_COMMISSION_WRITING_TEST,
    EXAM_COMMISSION_SPEAKING_TEST,
    ENTRANCE_EXAMINATION,
    MANAGEMENT,
    DOCTORALS_CONSULTING
}
