cad:
  generation:
    path:
      curriculum:
        ~/tmp/genration
      workplan:
        ~/tmp/generation
      k3:
        ~/tmp/generation
  allowed-origins:
    urls:
      - http://localhost:4200
      - http://localhost:8088
      - http://localhost:4200/subject-load
      - http://localhost:8088/subject-load
    headers:
      - content-type
spring:
  mvc:
    dispatch-options-request: true
