cad:
  generation:
    path:
      curriculum:
        ~/tmp/genration
      workplan:
        ~/tmp/generation
      k3:
        ~/tmp/generation
  allowed-origins:
    urls:
      - http://localhost:4200
      - http://localhost:8088
      - http://localhost:4200/subject-load
      - http://localhost:8088/subject-load
    headers:
      - content-type
spring:
  main:
    lazy-initialization: false
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  mvc:
    dispatch-options-request: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

google:
  drive:
    credentials:
      type: ${GD_CRED_TYPE}
      project-id: ${GD_CRED_PROJ_ID}
      private-key-id: ${GD_CRED_PRIV_KEY_ID}
      private-key: ${GD_CRED_PRIV_KEY}
      client-email: ${GD_CRED_CLIENT_EMAIL}
      client-id: ${GD_CRED_CLIENT_ID}
      auth-uri: ${GD_CRED_AUTH_URI}
      token-uri: ${GD_CRED_TOKEN_URI}
      auth-provider-x509-cert-url: ${GD_CRED_AUTH_PROVIDER_X509_CERT_URL}
      client-x509-cert-url: ${GD_CRED_CLIENT_X509_CERT_URL}
